spring:
  kafka:
    bootstrap-servers: kafka-broker-1:9092,kafka-broker-2:9093,kafka-broker-3:9094
    consumer:
      group-id: ticket-reservation-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      retries: 3
      acks: all
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: Ticket Reservation System
  data:
    mongodb:
      uri: mongodb+srv://admin:{}@cluster0.7kzjasa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ticket-reservation

springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      url: /swagger-ui
