openapi: 3.0.1
info:
  title: Movie Reservation API
  description: API documentation for the Movie Reservation system
  version: 1.0.0

paths:
  /getAllShows:
    get:
      summary: Get all available shows
      description: Retrieve a list of shows for given set of parameters. The movie name can be a partial match.
      tags:
        - Shows
      parameters:
        - name: movieName
          in: query
          description: The name of the movie to search for
          required: false
          schema:
            type: string
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of shows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetAllShowsResponseItem'
        '404':
          description: Movie not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllShowsError'

  /bookMovieTickets:
    post:
      summary: Book a particular show
      description: Book a show with a specific movie and date
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookMovieTicketRequest'
      responses:
        '200':
          description: Booked successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookMovieTicketResponse'

components:
  schemas:
    GetAllShowsResponseItem:
      type: object
      required:
        - id
        - movieName
        - date
        - startTime
        - endTime
      properties:
        id:
          type: integer
        movieName:
          type: string
        date:
          type: string
          format: date
        startTime:
          type: string
          example: "18:00"
        endTime:
          type: string
          example: "20:30"

    BookMovieTicketRequest:
      type: object
      required:
        - movieName
        - time
      properties:
        movieName:
          type: string
        time:
          type: string
          example: "2025-04-28T18:00:00Z"

    BookMovieTicketResponse:
      type: object
      required:
        - bookingId
        - movieName
        - time
        - status
      properties:
        bookingId:
          type: string
        movieName:
          type: string
        time:
          type: string
        status:
          type: string
          example: "CONFIRMED"

    GetAllShowsError:
      type: object
      required:
        - errorMessage
      properties:
        errorMessage:
          type: string