openapi: 3.0.1
info:
  title: Movie Reservation API
  description: API documentation for the Movie Reservation system
  version: 1.0.0
paths:
  /getAllShows:
    get:
      summary: Get all available shows
      description: Retrieve a list of shows for given set of parameters. The movie name can be a partial match.
      tags:
        - Shows
      parameters:
        - name: movieName
          in: query
          description: The name of the movie to search for
          schema:
            type: string
        - name: date
          in: query
          description: The date for which movies are required
          schema:
            type: string
      responses:
        '200':
          description: A list of shows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getAllShowsResponse'
        '404':
          description: Movie not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllShowsError'

  /bookMovieTickets:
    post:
      summary: Book a particular show
      description: Book a show with a specific movie and date
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bookMovieTicketRequest'
      responses:
        '200':
          description: Booked successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookMovieTicketResponse'
components:
  schemas:
    getAllShowsResponse:
      type: object
      properties:
        id:
          type: integer
        movieName:
          type: string
        date:
          type: string
        startTime:
          type: string
        endTime:
          type: string
    bookMovieTicketRequest:
      type: object
      properties:
        movieName:
          type: string
        time:
          type: string
    bookMovieTicketResponse:
      type: object
      properties:
        bookingId:
          type: string
        movieName:
          type: string
        time:
          type: string
        status:
          type: string
    getAllShowsError:
      type: object
      properties:
        errorMessage:
          type: string